### ISSUE TITLE
AttributeError: module 'theano' has no attribute 'gof'

### ISSUE THREAD

**Issue by darentsia** [chrisspen/punctuator2#1] opened 2020-06-15 14:56 UTC
Hello! I'm trying to use your punctuator as a module in python. 
However, when I'm trying to import it, I get this type of error: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-733b151e9f3c> in <module>
----> 1 from punctuator import Punctuator

~/projects/parser/env/lib/python3.6/site-packages/punctuator/__init__.py in <module>
      2 __version__ = '.'.join(map(str, VERSION))
      3 try:
----> 4     from .punc import Punctuator
      5 except ImportError as exc:
      6     import traceback

~/projects/parser/env/lib/python3.6/site-packages/punctuator/punc.py in <module>
     10 from io import open, StringIO
     11 
---> 12 import theano
     13 import theano.tensor as T
     14 import numpy as np

~/projects/parser/env/lib/python3.6/site-packages/theano/__init__.py in <module>
    108     object2, utils)
    109 
--> 110 from theano.compile import (
    111     SymbolicInput, In,
    112     SymbolicOutput, Out,

~/projects/parser/env/lib/python3.6/site-packages/theano/compile/__init__.py in <module>
     10 from theano.compile.function_module import *
     11 
---> 12 from theano.compile.mode import *
     13 
     14 from theano.compile.io import *

~/projects/parser/env/lib/python3.6/site-packages/theano/compile/mode.py in <module>
    379 # string as the key
    380 # Use VM_linker to allow lazy evaluation by default.
--> 381 FAST_COMPILE = Mode(theano.gof.vm.VM_Linker(use_cloop=False, c_thunks=False),
    382                     'fast_compile')e
    383 if theano.config.cxx:

AttributeError: module 'theano' has no attribute 'gof'
```

I'm using virtualenv to install all of the necessary dependencies. 
I have python3.6, Theano-1.0.4. 

All of the ways to solve this problem suggest to use conda, but I don't want to use conda, I prefer virtualenv only. 

Thank you!

**Comment by chrisspen** [comment] 2020-10-20 23:08
Can you post the commands you used to create your environment, and a call that reproduces the problem?

I'm running it under Python3.7 and same Theano verseion, and I didn't get any Theano error.

**Comment by chrisspen** [comment] 2020-12-28 14:09
I can't reproduce this problem on my end. Looks like it's probably a Theano bug, which I can't resolve on my end.

Closing this as not reproducible. Feel free to re-open if you can provide a script with steps to reproduce.

**Closed as completed by chrisspen** 2020-12-28 14:09 UTC
